### ISSUE TITLE
Cast vs. Call

### ISSUE THREAD

**Issue by capitalist** [pragdave/jeeves#1]
What do you think of a convention for functions where you're interested only in the side effect not the return value.

So, could Service cast instead of call if the function ended in `:noreply` perhaps? Would this be useful?

**Comment by pragdave** [comment]
I thought about that, but for a service you typically want it to be synchronous, so you're unlikely to see a difference at the client API. For that reason, I chose to use calls for everything.

One this I _don't_ want to do it to provide 100% of GenServer functionality. I just want to make it easy to do a basic service.

But I'm open to be convinced.

**Comment by capitalist** [comment]
Hmm, that makes perfect sense. Casts are usually for updating the state held, but as a service you'd typically expect a reply. 

I'll have plenty of time on my drive home Friday to try and think of a use case, or not. So, on Saturday I'll try to pitch you on it - or close the issue.

**Comment by capitalist** [comment]
So, how about something like this - an ecommerce event tracker sending events to statsd

```elixir
defmodule EcommerceEventTracker do
  use Service.Named, state: %{ host: 'localhost', port: 8125}

  @moduledoc """
  This service allows us to fire ecommerce events at statsd as they happen
  """

  @@doc """
  Record a login by incrementing the counter
  """
  def login do
    "login"
    |> statsd_count_message
    |> send_message
  end

  @@doc """
  Record an add_to_cart by incrementing the counter
  """
  def add_to_cart do
    "add_to_cart"
    |> statsd_count_message
    |> send_message
  end

  @@doc """
  Record how long a checkout took
  """
  def checkout_duration(time) do
    "checkout_time"
    |> statsd_timer_message(time)
    |> send_message
  end

  @@doc """
  Report active cart count
  """
  def active_carts(num) do
    "active_carts"
    |> statsd_guage_message(num)
    |> send_message
  end

  defp send_message(msg) do
    {:ok, socket} = :gen_udp.open(0, [:binary])
    :gen_udp.send(socket, state.host, state.port, msg)
    :gen_udp.close(socket)
    :noreply
  end

  defp statsd_count_message(name) do
    # todo
  end

  defp statsd_timer_message(name, val) do
    # todo
  end

  defp statsd_guage_message(name, val) do
    # todo
  end

end
```

**Comment by capitalist** [comment]
the thing with this code, is you'd need something that signals to the macro to use a cast instead of a call right? ... maybe it needs to be a function naming convention?

**Comment by pragdave** [comment]
I can do that automatically (by looking for calls to `set_state`. But it worries me—where does the back pressure come from?

**Comment by capitalist** [comment]
Hmm, I'm not sure you'd need back pressure in this case. That's part of the statsd philosophy. The way the stats are tracked, it's ok to just hammer it with UDP and let it drop packets it can't handle.

It sounds like, though, you're worried about the receiver getting more messages in the mailbox than it can handle and filling memory. By using call, the sender would have to wait for acknowledgement before sending another message - thus adding back pressure to the system. For that, I do not have an answer. But nor does regular cast in OTP right? i.e. here has always been dragons. 

Or maybe I'm misunderstanding completely.

**Comment by chrismccord** [comment]
Yup, here has always been dragons, so I would be really hesitant to automatically infer cast vs call because it is something that is necessarily required to think about when designing the system. Back-pressure is generally a good thing and fire-and-forget casting is something you need to be super careful of when doing. I think having everything as calls by default as it is now is a good thing.

**Comment by capitalist** [comment]
Another 8 minutes of consideration has brought me around to this view point as well. Service is not == GenServer - instead, it's a tool designed to create, well, a Service. And a Service in a distributed system should certainly have backpressure. A Caster is something else.
